### ISSUE TITLE
Credentials for MSIX packaging tool to connect to created VM unclear

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/msix-docs#15]
I created a VM using Hyper-V Quick Create and the MSIX VM template.

In the MSIX packaging tool I can select the VM and then I need to supply credentials to access the VM. What are those credentials?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca58f5e-1347-f9de-b102-ac0be796858a
* Version Independent ID: 6a087cdf-5ac1-0f9b-a6f3-219982821120
* Content: [MSIX packaging environment on Hyper-V Quick Create - MSIX](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/quick-create-vm)
* Content Source: [msix-src/packaging-tool/Quick-Create-VM.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/packaging-tool/Quick-Create-VM.md)
* Product: **msix**
* GitHub Login: @c-don
* Microsoft Alias: **cdon**

**Comment by c-don** [comment]
The credentials are used to login to the VM. so provide the credentials that you would generally use to login.

**Comment by hansmbakker** [comment]
After the creation of the VM I understood that you have to create a local account and for that setup it works.

If you create a VM using Windows Pro yourself using a personal Microsoft account rather than a local account - how do you supply those credentials to the MSIX packaging tool in that case?

**Comment by c-don** [comment]
You should be able to provide the domain\username and then the password. 

@sharlaakers can you correct me if i am wrong?

**Comment by hansmbakker** [comment]
So if people have an @hotmail.com or @outlook.com personal Microsoft account, how would that work?

**Comment by c-don** [comment]
There was a bug that was resolved in the 1904 release of Windows 10 which didnt allow for 'email' format usernames. The current quick create VM is based of 1809 release of Windows 10. 

You should be able to connect to VM using the personal microsoft account, as long as the VM is 1904 release of Windows 10.

**Comment by hansmbakker** [comment]
(I [filed that as a bug in Feedback Hub](https://aka.ms/AA308xw) half a year ago, but never got a reply, so I assumed the bug would still exist)
